set(CMAKE_SYSTEM_NAME Generic)
set ( CMAKE_C_FLAGS "-mthumb -mcpu=cortex-m3 -mfloat-abi=soft -fmessage-length=0 -ffunction-sections -g -gdwarf-2" )
set ( CMAKE_CXX_FLAGS "-mthumb -mcpu=cortex-m3 -mfloat-abi=soft -fmessage-length=0 -ffunction-sections  -fno-exceptions -fno-rtti -g -gdwarf-2" )
set ( CMAKE_ASM_FLAGS "-mthumb -mcpu=cortex-m3 -mfloat-abi=soft -x assembler-with-cpp" )
set ( CMAKE_EXE_LINKER_FLAGS "-mthumb -mcpu=cortex-m3 -mfloat-abi=soft --specs=nano.specs --specs=nosys.specs -lc -lm -lnosys -Wl,--gc-sections" )